### ISSUE TITLE
As a web development student, I want to be able to login with my Github account and see who and when visited the company card last time

### ISSUE THREAD

**Issue by Reinoptland** [You-Can-Code-It/fndr#5]
![Image](https://github.com/You-Can-Code-It/fndr/assets/20372832/fd630eb6-bb49-4e20-8d36-d421332560c4)

- [x]  Setup NextAuth + Update schema

- [x] Test adding event with date

# As a web development student that is part of the You Can Code It community, I want to see when another student recently looked at a company, so I can save time

I think at this point Marina managed to:

- Update the database schema and added the UserEvent model
- Is able to insert a UserEvent by clicking a button

How to continue and ship this feature?

You can write your own, but here is an outline I wrote below in the toggle

<details>
    <summary>Plan</summary>

It will be hard to combine your work when you don't have access to the UI elements and company list which was added by Gulnara & Luiz.
So the first step is to either update your branch or make pullrequest with what you have a and pull development. The second option is probably the easiest. So let's start with that

- [x] Push what you have and make ap pullrequest.
- [x] If you get some merge conflict, click "solve on github" and ask Luiz / Gulnara to help you figure out what changes to keep.
- [x] Once you've merged the PR, go to your development branch on your machine (git checkout development) and pull (git pull origin development).
- [x] checkout to a new feature branch
- [x] In order to do testing justice your will need have data in your db So run the seed command (ask Luiz)

Now that you have the updates from the others you can try incorporate your work with theirs.

- [x] This interaction will be easier to program if there is a dedicated company card component, if there isn't one, put the current company card JSX into a seperate component that accepts props (maybe this component already exists, if so, use the existing component)
- [x] When you click on a company card, console log
- [x] Now try to console.log the id of the company
- [x] Now send the request to create a UserEvent for this user + company
- [x] Check to see if the backend code is still working
- [x] In order to display the latest user event for the cards, change the database query that fetches the companies, you want to `include` userEvents, order them by createdAt desc and take 1 (that way you will have the latest one). For the userEvent `include` the user as well. (that way you can show the avatar of the user), this query might be challenging to write, so look at the docs carefully orr do it together with Luiz / Gulnara (or ask chatgtp haha!)
- [x] When mapping the companies, pass the userEvent as props to the company card
- [x] Display the avatar and format the time interval (with Luxon? or maybe DayJS)

Now there is still showing the user event right after you click the card (without needing to refresh)

- [x] Create a state to store who visited this card last maybe call it`[latestUserEvent, setLatestUserEvent]`
- [x] This initial state for this data is the userEvent you are now passing as props (if there is one)
- [x] When the response comes back after you create a user event, you can setLatetsUserEvent to update the card without a refresh.

Now clean up, if there are TypeScript types that need to be added ask for some help if needed, make a PR and tag Gulnara / Luiz or a review

</details>

**Comment by Reinoptland** [comment]
@korvenhasta I updated this with a plan!

**Comment by korvenhasta** [comment]
Anything else: 

- I am sending to frontend userID. It's not a good idea to do this. Maybe we should improve this later
- Make better data visualization. For example: 
NO: seen 32 days ago by Marina
YES: seen 1 month ago by Marina
